// Generated by scripts/list-videos.mjs (runs before dev/build). Do not edit.
export const STEP_VIDEOS: readonly string[] = ["0.1","1.1","1.2","1.3","1.4","2.1","2.2","2.3","3.1"];
export const MODULE_INTROS: readonly string[] = [];
