// Generated by scripts/list-videos.mjs (runs before dev/build). Do not edit.
export const STEP_VIDEOS: readonly string[] = ["0.1","1.3","2.2","3.1","3.2","3.3","3.4","4.1","4.2","4.3","4.4","4.5","4.6","4.7","4.8","4.9","5.1","5.2","5.3","5.4","5.5","6.1"];
export const MODULE_INTROS: readonly string[] = [];
