// Writes src/content/videos.ts: the step / module-intro videos that exist in public/avatar.
// The site only requests these, so a missing video never stalls playback (the host
// answers unknown paths with the SPA page, which some browsers never reject).
import { readdirSync, writeFileSync } from "node:fs";

const files = readdirSync(new URL("../public/avatar/", import.meta.url));
const has = (ext) => new Set(files.filter((f) => f.endsWith(ext)).map((f) => f.slice(0, -ext.length)));
const mp4 = has(".mp4");
const webm = has(".webm");
const steps = [...mp4].filter((id) => /^\d+\.\d+$/.test(id) && webm.has(id)).sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
const intros = [...mp4].filter((id) => /^m\d+$/.test(id)).map((id) => id.slice(1)).sort();

writeFileSync(
  new URL("../src/content/videos.ts", import.meta.url),
  `// Generated by scripts/list-videos.mjs (runs before dev/build). Do not edit.\n` +
    `export const STEP_VIDEOS: readonly string[] = ${JSON.stringify(steps)};\n` +
    `export const MODULE_INTROS: readonly string[] = ${JSON.stringify(intros)};\n`,
);
console.log(`videos: ${steps.length} steps, ${intros.length} intros`);
